server:
  port: 30000
spring:
  application:
    name: third-party
  cloud:
    nacos:
      discovery:
        server-addr: 
    alicloud:
      access-key: 
      secret-key: 
      oss:
        endpoint: 
        bucket: gulimall-pumpkin
